spring:
  application:
    name: payday

  datasource:
    url: jdbc:mysql://mysql:3306/payday_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    root: info

  profiles:
   active: default

toss:
  secret-key: test_sk_AAAAAAA_fake_key

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method